### PR TITLE
Support SegWit

### PR DESCRIPTION
**Pull request by bitkevin**
Support SegWit. 

merged from https://github.com/theuni/btcpool/commit/f014154eaecb6821cf8e27f499c15cd09a10dfdb
- Advertise support for the segwit rule
- Grab default_witness_commitment from gbt
- Insert default_witness_commitment as 2nd txout

TODO:
- <del>Skip insertion if default_witness_commitment doesn't exist</del> done by https://github.com/btccom/btcpool/pull/9/commits/fa8891f7c85171c4933a888b39f5469b86b65b1d
- Verify that merkles are being built without witness data

### CODE REVIEW

**Comment by theuni** [comment]
Nice!

Is it possible to test this on testnet? I was not able to reliably test my patches, as I'm not familiar enough with btcpool to know how to troubleshoot. So they were written completely blindly.

It would be great to test 3 things here:
1. Mine a block on testnet that contains witness transactions
2. Mine a block on mainnet to make sure that nothing broke
3. Add a test in TestStratum.cc for a block that contains witness data. This will mean that hash != txid.

For 1 and 2, I recommend using a bitcoind patched with https://github.com/bitcoin/bitcoin/pull/9000. You can then start bitcoind using (for example) ```./bitcoind -forceminerdifficulty=493944831```

That will allow testing on any net (testnet or mainnet), except that forces bitcoind to "lie" about the difficulty, so that it can be set very low. In this mode, when blocks are submitted, they're simply tested (ignoring the fact that the difficulty is too low), then thrown away. No changes to mining software are necessary.

**Comment by bitkevin** [comment]
we have mined several segwit blocks on testnet3 which contains witness txs, one of blocks:

```
{
  "hash": "000000000000000a99bc67d90e283e0730e0db0a6d353bfa9aac1c4c479a26e3",
  "confirmations": 1,
  "strippedsize": 5379,
  "size": 5525,
  "weight": 21662,
  "height": 1064002,
  "version": 536870912,
  "versionHex": "20000000",
  "merkleroot": "af38f5f89e0e7fd8511cf6d34409454ba626d30b7e84801524e36f7e911618aa",
  "tx": [
    "33e1aa548a13f7f7df3422189c4021dcdfa5c81eb6189f03bc066b1e4221a840",
    "2cda3f2e07973e3f1464cc2c2ce9a71ec2cb95e436b702d615cacf4116facd7a",
    "f47d989085cee4e6bfe2f33672958cb8db7412f338bfeb86510b291c0ff2de8d",
    "6b358554265fb49ba23ad1bff5b9b12cb24450e852e16503902260fdc514a7da",
    "913dcb0aad24ce3dffb2ddc20bafe80b57a6afb4853483c491c8deeb1e818a40",
    "1547fbe0cd90a8e2e6c3307a0065dd9909fdae8665f4a0e806f1c798972a08ab",
    "905950ff1956eed8dd73e58c48513f4667155174c1cc09a2df1968251ee218bd",
    "2cf35b39190dce539c08aa050802b53dadfa3b936ad0ea988ac028f6bb447b92",
    "1575711428614e85251f3778ccc5d499d86a275765cab654375d5235fd7880a1",
    "2dd16cb412cb593b46c005a4819a9e8c8c0976a969ad5f8dd0a0efa5087644fd",
    "960e04ed1d785d26ef54aded3197f1b123d162aae39f4fe67ef547a84ea8aa76",
    "9d6ce01035b5c41988dd5bee812359f9c1b6683b6fe48fdf73762c537625fb7f",
    "1241e0d89ef7ddb4f2dd5eca59d766b4d934a54ec4a985828f35fe0e1699019e",
    "13089dc41621e7b78983d54d48d809565498570eeff6849782bc2800371393ab",
    "dc5e802ba9248833e43c175ac2511298545fddffdb87a6d160571386fd05e989"
  ],
  "time": 1483878717,
  "mediantime": 1483874762,
  "nonce": 691739001,
  "bits": "1a037666",
  "difficulty": 4845339.949056488,
  "chainwork": "00000000000000000000000000000000000000000000001d9de6013746d22014",
  "previousblockhash": "000000000000000e2afb810d01bb60d9c3bd3c1395d311b39c66f42a16f47acb"
}
```

**Comment by bitkevin** [comment]
Add a gist: [how to create witness transaction](https://gist.github.com/bitkevin/15763a5984870f68b68ab01da9d5d7e6), maybe could help someone when trying to make witness txs on testnet3.

tested on v0.13.1 and v0.13.2.

**Comment by bitkevin** [comment]
we have mined two blocks on `mainnet` which coinbase tx contains the witness commitment:

https://btc.com/0000000000000000022ffa9ed3046230b31a13f57faa5e7bb5bba653b5b6626b
https://btc.com/0000000000000000028a507cb15ef64f8b1a054dfd63ba316076a3e1392f32bb

**Pull request merged**
