### PR TITLE
Add Stratum version-rolling extension support

### PR DESCRIPTION
**Pull request by bagaluu**
Add support Stratum `version-rolling` support specified at http://stratumprotocol.org/

Note: AsicBoost have been [freely available](https://www.asicboost.com/single-post/2018/03/01/opening-asicboost-for-defensive-use/) under the [Blockchain DPL](https://blockchaindpl.org) since March 1, 2018

### CODE REVIEW

**Comment by YihaoPeng** [comment]
I noticed that AsicBoost is patent protected. Is there any patent risk for this commit?

**Comment by bagaluu** [comment]
Patent does not apply to pools supporting this extension as pools themselves are not implementing the patent invention.

This extension is supported by [Slushpool](https://twitter.com/slush_pool/status/971098024205275142), [ckpool](https://bitbucket.org/ckolivas/ckpool/commits/fc60b6d67f7a2aed3b7aae740469a855de4221d0), as well as patch exists for [Eloipool](https://github.com/luke-jr/eloipool/compare/verroll). I've linked to the sources of ckpool and eloipool. Slush is closed source and havent published the patch.

The license of the AsicBoost patent is sort of GPL like, in that equipment manufacturers are free to incorporate AsicBoost into their equipment so long as they adopt the same license. See the FAQ https://blockchaindpl.org/faq

"Defensive Use" simply means that you are not allowed to aggressively sue other `BDPL Users` for patent infringement of your own patents, and must reciprocally license your patents to other BDPL Users. "Defensive Licensing" is a principal that you dont attack others for patent infringement unless they attack you first. BDPL is tailored for the blockchain industry to help prevent patents from being used in a way that harms decentralization. For Bitcoin mining this is especially important. AsicBoost is very useful and the reward for getting to use it means less risk from patents being used to harm competition which is important for mining and for Bitcoin decentralization.

**Comment by dyzz** [comment]
We are still reviewing the BDPL. It could be a careful and lengthy process.

**Comment by webchi** [comment]
Hello. Yesterday we tested this pull request with Dragonmint T1 miner and its well connected. 
But miner speed was about 4 TH insted of its real 16 TH. And on ckpool we get 18TH. 
Also after we connect Antminer without asicboost and have it own 17 GH speed. 
Could be this issue of current realization of asicboost protocol? Or another one?

**Comment by dyzz** [comment]
we haven’t tested with Dragonmint miner yet. Can you share some logs?




| |
Zhong Zhuang
邮箱：naituida@163.com
|

签名由 网易邮箱大师 定制

On 05/31/2018 15:52, Vasiliy wrote:

Hello. Yesterday we tested this pull request with Dragonmint T1 miner and its well connected.
But miner speed was about 4 TH insted of its real 16 TH. And on ckpool we get 18TH.
Also after we connect Antminer without asicboost and have it own 17 GH speed.
Could be this issue of current realization of asicboost protocol? Or another one?

**Comment by YihaoPeng** [comment]
Let me list some cases that not related with AsicBoost.
BTCPool's `sserver` may have the following differences compared to other mining pools':

1. We use 8 bytes ExtraNonce2. Some pool only use 4 bytes.
2. Our job id is rotated. That is, looping from 0 to 9 continuously. Some mining programs may require a globally unique job id. (We do special processing for the client of NiceHash, giving it a globally unique job id. See https://github.com/btccom/btcpool/blob/7baa93acc6381a0658217994adaf3acdcb80b0dd/src/StratumSession.cc#L689)

**Comment by webchi** [comment]
Is it enough to just change this rows or need deeper changes? We tried but have no success.

**Comment by webchi** [comment]
Logs are not informative. Miner only say that he connect to pool. Pool sad that miner connected. 
It seems need to go deeper to understand why so bad hashrate we have.

**Comment by YihaoPeng** [comment]
Uncomment line 971 of StratumSession.cc and make a debug build of `sserver`.
```
void StratumSession::sendData(const char *data, size_t len) {
  // add data to a bufferevent’s output buffer
  // it is automatically locked so we don't need to lock
  bufferevent_write(bev_, data, len);
  DLOG(INFO) << "send(" << len << "): " << data; //uncomment this line
}
```

It will log all datas it sent to miner or received from miner.

And we can observation and analysis with the log.

**Comment by YihaoPeng** [comment]
@webchi To enable a unique job id, change this line from `false` to `true` may help:
https://github.com/btccom/btcpool/blob/7baa93acc6381a0658217994adaf3acdcb80b0dd/src/StratumSession.cc#L234

**Pull request merged**
